//! The CLI reference page, walked from the clap definition of `conductor`
//! (`conductor_cli::cli::Cli`).

use clap::CommandFactory;

use crate::{SOURCE, cell, front_matter};

/// Where the CLI reference lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/cli.md";

/// Every subcommand below `command`, depth first, without clap's `help`.
fn commands(command: &clap::Command, out: &mut Vec<clap::Command>) {
    for sub in command.get_subcommands() {
        if sub.get_name() == "help" {
            continue;
        }
        out.push(sub.clone());
        commands(sub, out);
    }
}

/// The heading anchor Docusaurus gives ``## `conductor watch run` ``.
fn anchor(command: &clap::Command) -> String {
    command
        .get_bin_name()
        .unwrap_or(command.get_name())
        .replace(' ', "-")
}

fn text(value: Option<&clap::builder::StyledStr>) -> String {
    value.map(ToString::to_string).unwrap_or_default()
}

/// One row per argument of `command`, its global ones when `global` and its own otherwise: how it
/// is written, whether it is required, its default and its help.
fn arguments(command: &clap::Command, global: bool) -> Vec<[String; 4]> {
    command
        .get_arguments()
        .filter(|arg| !matches!(arg.get_id().as_str(), "help" | "version"))
        .filter(|arg| arg.is_global_set() == global)
        .map(|arg| {
            let value = arg
                .get_value_names()
                .and_then(|names| names.first().map(ToString::to_string))
                .unwrap_or_else(|| arg.get_id().as_str().to_uppercase());
            let written = match arg.get_long() {
                Some(long) if !arg.get_action().takes_values() => format!("--{long}"),
                Some(long) => format!("--{long} <{value}>"),
                None => format!("<{value}>"),
            };
            let defaults: Vec<String> = arg
                .get_default_values()
                .iter()
                .map(|default| default.to_string_lossy().into_owned())
                .collect();
            let possible: Vec<String> = arg
                .get_possible_values()
                .iter()
                .filter(|value| !value.is_hide_set())
                .map(|value| format!("`{}`", value.get_name()))
                .collect();
            let mut help = text(arg.get_long_help().or(arg.get_help()));
            if arg.get_action().takes_values() && !possible.is_empty() {
                help = format!("{help} One of {}.", possible.join(", "))
                    .trim_start()
                    .to_owned();
            }
            [
                format!("`{written}`"),
                if arg.is_required_set() { "yes" } else { "no" }.to_owned(),
                if defaults.is_empty() {
                    "none".to_owned()
                } else {
                    format!("`{}`", defaults.join(", "))
                },
                cell(&help),
            ]
        })
        .collect()
}

fn table(rows: &[[String; 4]]) -> String {
    let mut out = String::from("| Argument | Required | Default | Meaning |\n|---|---|---|---|\n");
    for row in rows {
        out.push_str(&format!("| {} |\n", row.join(" | ")));
    }
    out
}

/// The CLI reference page for the command line `root`.
#[must_use]
pub fn page_for(mut root: clap::Command) -> String {
    root.build();
    let name = root.get_name().to_owned();
    let mut all = Vec::new();
    commands(&root, &mut all);

    let mut out = front_matter(
        "CLI reference",
        1,
        &format!(
            "Every command and option of the {name} command line, generated from its definition."
        ),
    );
    out.push_str(&format!(
        "# `{name}`\n\nGenerated by `conductor-docs` from the clap definition of the `{name}` \
         command line in [`crates/conductor/src/cli.rs`]({SOURCE}/crates/conductor/src/cli.rs). It \
         lists only commands that exist; `--help` after any command prints the same text.\n\n> {}\n\n\
         ## Global options\n\nEvery command takes these, before or after its name.\n\n{}\n\
         ## Commands\n\n| Command | What it does |\n|---|---|\n",
        cell(&text(root.get_about())),
        table(&arguments(&root, true)),
    ));
    for command in &all {
        let written = command.get_bin_name().unwrap_or(command.get_name());
        out.push_str(&format!(
            "| [`{written}`](#{}) | {} |\n",
            anchor(command),
            cell(&text(command.get_about()))
        ));
    }
    for command in &mut all {
        let written = command
            .get_bin_name()
            .unwrap_or(command.get_name())
            .to_owned();
        let about = cell(&text(command.get_long_about().or(command.get_about())));
        let about = if about.is_empty() {
            String::new()
        } else {
            format!("{about}\n\n")
        };
        out.push_str(&format!(
            "\n## `{written}`\n\n{about}```text\n{}\n```\n",
            command.render_usage().to_string().trim_end()
        ));
        let rows = arguments(command, false);
        if !rows.is_empty() {
            out.push('\n');
            out.push_str(&table(&rows));
        }
        let after = text(command.get_after_long_help().or(command.get_after_help()));
        if !after.is_empty() {
            out.push_str(&format!("\n```text\n{}\n```\n", after.trim_end()));
        }
    }
    out
}

/// The CLI reference page for `conductor`.
#[must_use]
pub fn page() -> String {
    page_for(conductor_cli::cli::Cli::command())
}
