//! The crate list, from `cargo metadata --no-deps`: every workspace package, its directory, the
//! name Rust code uses for it, and its `description`.

use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail, ensure};
use serde_json::Value;

use crate::{TREE, cell, front_matter};

/// Where the crate list lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/crates.md";

/// One workspace package as the page lists it.
#[derive(Debug, PartialEq, Eq)]
struct Package {
    name: String,
    directory: String,
    /// The library name (`use <lib>`), when the package has a library.
    lib: Option<String>,
    /// The binaries it builds.
    bins: Vec<String>,
    description: String,
}

/// The packages of a `cargo metadata --format-version 1` document, sorted by name, with their
/// directories relative to `workspace_root`. A package without a description is refused: the page
/// would have nothing to say about it.
fn packages(metadata: &Value) -> Result<Vec<Package>> {
    let root = metadata["workspace_root"]
        .as_str()
        .context("cargo metadata names no workspace_root")?;
    let mut found = Vec::new();
    for package in metadata["packages"]
        .as_array()
        .context("cargo metadata lists no packages")?
    {
        let name = package["name"]
            .as_str()
            .context("a package has no name")?
            .to_owned();
        let manifest = package["manifest_path"]
            .as_str()
            .with_context(|| format!("{name} has no manifest_path"))?;
        let directory = Path::new(manifest)
            .parent()
            .and_then(|dir| dir.strip_prefix(root).ok())
            .with_context(|| format!("{name} lies outside the workspace"))?
            .to_string_lossy()
            .replace('\\', "/");
        let Some(description) = package["description"].as_str() else {
            bail!("{name} has no description in its Cargo.toml");
        };
        let mut lib = None;
        let mut bins = Vec::new();
        for target in package["targets"].as_array().into_iter().flatten() {
            let kinds: Vec<&str> = target["kind"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect();
            let target_name = target["name"].as_str().unwrap_or_default().to_owned();
            if kinds.contains(&"lib") {
                lib = Some(target_name.replace('-', "_"));
            } else if kinds.contains(&"bin") {
                bins.push(target_name);
            }
        }
        bins.sort();
        found.push(Package {
            name,
            directory,
            lib,
            bins,
            description: description.trim().to_owned(),
        });
    }
    ensure!(!found.is_empty(), "cargo metadata lists no packages");
    found.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(found)
}

/// The crate list page for the packages of `metadata`.
fn page_for(metadata: &Value) -> Result<String> {
    let all = packages(metadata)?;
    let mut out = front_matter(
        "Crates",
        3,
        "Every package of the conductor workspace, generated from cargo metadata.",
    );
    out.push_str(&format!(
        "# Crates\n\nGenerated by `conductor-docs` from `cargo metadata --no-deps`: every package of \
         the workspace, with the `description` its `Cargo.toml` gives. There are {} packages. None \
         is on a registry; build them from the repository. The domain types live in \
         `crates/conductor-model`, which `ess` generates from `spec/` and which is outside the \
         workspace.\n\n| Package | Directory | In Rust | What it is |\n|---|---|---|---|\n",
        all.len(),
    ));
    for package in &all {
        let mut uses = Vec::new();
        if let Some(lib) = &package.lib {
            uses.push(format!("`use {lib}`"));
        }
        for bin in &package.bins {
            uses.push(format!("binary `{bin}`"));
        }
        out.push_str(&format!(
            "| `{}` | [`{dir}`]({TREE}/{dir}) | {} | {} |\n",
            package.name,
            uses.join(", "),
            cell(&package.description),
            dir = package.directory,
        ));
    }
    Ok(out)
}

/// The crate list page for the workspace at `root`, read with `cargo metadata`.
///
/// # Errors
///
/// When `cargo metadata` fails or a package has no description.
pub fn page(root: &Path) -> Result<String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(&cargo)
        .args([
            "metadata",
            "--no-deps",
            "--format-version",
            "1",
            "--manifest-path",
        ])
        .arg(root.join("Cargo.toml"))
        .output()
        .context("running cargo metadata")?;
    if !output.status.success() {
        bail!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let metadata: Value =
        serde_json::from_slice(&output.stdout).context("parsing cargo metadata")?;
    page_for(&metadata)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn metadata(description: Option<&str>) -> Value {
        serde_json::json!({
            "workspace_root": "/w",
            "packages": [
                {
                    "name": "conductor-docs",
                    "manifest_path": "/w/crates/conductor-docs/Cargo.toml",
                    "description": "Generates pages.",
                    "targets": [
                        {"kind": ["lib"], "name": "conductor_docs"},
                        {"kind": ["bin"], "name": "conductor-docs"}
                    ]
                },
                {
                    "name": "conductor-cli",
                    "manifest_path": "/w/crates/conductor/Cargo.toml",
                    "description": description,
                    "targets": [
                        {"kind": ["lib"], "name": "conductor_cli"},
                        {"kind": ["bin"], "name": "conductor"},
                        {"kind": ["test"], "name": "config"}
                    ]
                }
            ]
        })
    }

    #[test]
    fn packages_are_sorted_and_linked() {
        let page = page_for(&metadata(Some("The command | line."))).unwrap();
        assert!(page.contains("There are 2 packages."));
        let cli = page.find("| `conductor-cli` |").unwrap();
        let docs = page.find("| `conductor-docs` |").unwrap();
        assert!(cli < docs);
        assert!(page.contains(
            "| `conductor-cli` | [`crates/conductor`](https://github.com/beyond10x/conductor/tree/main/crates/conductor) | `use conductor_cli`, binary `conductor` | The command \\| line. |"
        ));
    }

    #[test]
    fn a_package_without_a_description_is_refused() {
        let error = page_for(&metadata(None)).unwrap_err().to_string();
        assert!(
            error.contains("conductor-cli has no description"),
            "{error}"
        );
    }

    #[test]
    fn the_workspace_lists_every_member() {
        let page = page(&crate::repository_root()).unwrap();
        for dir in ["crates/conductor", "crates/conductor-docs"] {
            assert!(page.contains(&format!("[`{dir}`]")), "{dir}");
        }
    }
}
