#![forbid(unsafe_code)]
//! Generates the derivable part of the conductor documentation site, checks it for drift, and
//! binds a built site to its source commit. The site build itself is Docusaurus.
//!
//! It generates, under `website/`:
//!
//! - the CLI reference ([`cli`], `docs/reference/cli.md`), walked from the clap definition of
//!   `conductor` (`conductor_cli::cli::Cli`);
//! - the config reference ([`config`], `docs/reference/config.md`), from the specification
//!   `spec/domains/config.yaml` and the defaults `conductor_cli::config` fills;
//! - the crate list ([`crates`], `docs/reference/crates.md`), from `cargo metadata --no-deps`;
//! - the status data and page ([`status`], `data/status.json` and `docs/status.md`), from the
//!   capability list this crate holds.
//!
//! Every page is plain Markdown that the unified documentation site accepts ([`pages`]); the check
//! holds every Markdown page under `website/docs` to that, generated or written by hand.

pub mod cli;
pub mod config;
pub mod crates;
pub mod pages;
pub mod routes;
pub mod status;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, ensure};

/// The first line of every generated page's front matter.
pub const FRONT_MATTER_HEADER: &str = "# generated by conductor-docs, do not edit";
/// The line every generated Markdown page carries directly after its front matter.
pub const HEADER: &str = "<!-- generated by conductor-docs, do not edit -->";
/// A file in the repository on GitHub, by path.
pub const SOURCE: &str = "https://github.com/beyond10x/conductor/blob/main";
/// A directory in the repository on GitHub, by path.
pub const TREE: &str = "https://github.com/beyond10x/conductor/tree/main";
/// The directory the generator owns entirely, relative to the repository root.
pub const REFERENCE: &str = "website/docs/reference";
/// Every documentation page, generated or written by hand, relative to the repository root.
pub const DOCS: &str = "website/docs";

/// Generated files keyed by their path relative to the repository root.
pub type Outputs = BTreeMap<String, String>;

/// The repository root of this crate's own checkout.
#[must_use]
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// `value` as a double-quoted YAML string.
#[must_use]
pub fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `value` as one Markdown table cell: on one line, with `|` escaped, and passive outside code.
#[must_use]
pub fn cell(value: &str) -> String {
    prose(
        &value
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ")
            .replace('|', "\\|"),
    )
}

/// `text` with what MDX would execute escaped outside its code spans: `{` as `\{`, and the `<` that
/// opens a tag as `&lt;`, so that a placeholder such as `<name>` in prose is shown, not taken as
/// HTML.
#[must_use]
pub fn prose(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find('`') {
        out.push_str(&escape(&rest[..start]));
        let run = rest[start..].bytes().take_while(|b| *b == b'`').count();
        let after = &rest[start + run..];
        match pages::span_end(after, run) {
            Some(end) => {
                out.push_str(&rest[start..start + run + end + run]);
                rest = &after[end + run..];
            }
            None => {
                out.push_str(&rest[start..start + run]);
                rest = after;
            }
        }
    }
    out.push_str(&escape(rest));
    out
}

fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for (at, c) in text.char_indices() {
        match c {
            '{' => out.push_str("\\{"),
            '<' if text[at + 1..]
                .trim_start_matches('/')
                .starts_with(|c: char| c.is_ascii_alphabetic()) =>
            {
                out.push_str("&lt;");
            }
            _ => out.push(c),
        }
    }
    out
}

/// The front matter of a generated page and its generator line.
#[must_use]
pub fn front_matter(title: &str, position: u32, description: &str) -> String {
    format!(
        "---\n{FRONT_MATTER_HEADER}\ntitle: {}\nsidebar_position: {position}\ndescription: {}\ncustom_edit_url: null\n---\n\n{HEADER}\n\n",
        yaml_string(title),
        yaml_string(description),
    )
}

/// Every generated file for the repository at `root`, each Markdown page checked passive.
///
/// # Errors
///
/// When a source cannot be read, a shipped capability names a test that does not exist, or a
/// page would hold what the unified site refuses.
pub fn outputs(root: &Path) -> Result<Outputs> {
    let mut out = Outputs::new();
    out.insert(cli::PAGE.to_owned(), cli::page());
    out.insert(config::PAGE.to_owned(), config::page(root)?);
    out.insert(crates::PAGE.to_owned(), crates::page(root)?);
    out.insert(status::DATA.to_owned(), status::data(root)?);
    out.insert(status::PAGE.to_owned(), status::page(root)?);
    for (path, content) in &out {
        if path.ends_with(".md") {
            let problems = pages::problems(content);
            ensure!(
                problems.is_empty(),
                "{path} would not be passive Markdown: {}",
                problems.join(", ")
            );
            ensure!(!content.contains("story:"), "{path} would name a story");
        }
    }
    Ok(out)
}

/// Writes `outputs` under `out`, replacing everything under [`REFERENCE`] there.
///
/// # Errors
///
/// When a file cannot be written.
pub fn write(outputs: &Outputs, out: &Path) -> Result<()> {
    let reference = out.join(REFERENCE);
    if reference.exists() {
        fs::remove_dir_all(&reference)
            .with_context(|| format!("removing {}", reference.display()))?;
    }
    for (path, content) in outputs {
        let target = out.join(path);
        if let Some(dir) = target.parent() {
            fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        }
        fs::write(&target, content).with_context(|| format!("writing {}", target.display()))?;
    }
    Ok(())
}

/// Every file under `dir`, relative to `base`, with `/` separators.
fn files_under(base: &Path, dir: &Path, found: &mut Vec<String>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    let mut entries: Vec<_> = fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .collect::<Result<_, _>>()?;
    entries.sort_by_key(fs::DirEntry::path);
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            files_under(base, &path, found)?;
        } else {
            found.push(
                path.strip_prefix(base)?
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
    Ok(())
}

/// Every difference between `outputs` and the files under `out`: a missing file, a stale or edited
/// one, a file under [`REFERENCE`] the generator does not write, and every place a Markdown page
/// under [`DOCS`] holds what the unified site refuses.
///
/// # Errors
///
/// When a directory cannot be read.
pub fn check(outputs: &Outputs, out: &Path) -> Result<Vec<String>> {
    let mut problems = Vec::new();
    for (path, content) in outputs {
        match fs::read_to_string(out.join(path)) {
            Err(_) => problems.push(format!("missing {path}")),
            Ok(found) if &found != content => problems.push(format!("stale or edited {path}")),
            Ok(_) => {}
        }
    }
    let mut present = Vec::new();
    files_under(out, &out.join(REFERENCE), &mut present)?;
    for path in present {
        if !outputs.contains_key(&path) {
            problems.push(format!("not generated {path}"));
        }
    }
    let mut docs = Vec::new();
    files_under(out, &out.join(DOCS), &mut docs)?;
    for path in docs.iter().filter(|path| path.ends_with(".md")) {
        let text = fs::read_to_string(out.join(path))?;
        for problem in pages::problems(&text) {
            problems.push(format!("{path}:{problem}"));
        }
    }
    Ok(problems)
}

/// The project-site publication record for one build of the `/conductor/` site.
///
/// # Errors
///
/// When `commit` is not a nonzero full Git revision.
pub fn site_manifest(commit: &str) -> Result<String> {
    ensure!(
        commit.len() == 40
            && commit.bytes().all(|b| b.is_ascii_hexdigit())
            && commit != "0".repeat(40),
        "commit must be a nonzero full Git revision"
    );
    Ok(format!(
        "{{\n  \"baseUrl\": \"{}\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"conductor\",\n  \"schema\": \"b10x-project-site/v1\"\n}}",
        routes::BASE
    ))
}

/// Binds the built site at `site` to `commit`: `.well-known/b10x-site.json`, the route inventory
/// `.well-known/b10x-routes.json` and `.nojekyll`.
///
/// # Errors
///
/// When the commit is not a full revision, `site` holds no built site, or a file cannot be
/// written.
pub fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    ensure!(
        site.join("index.html").is_file(),
        "{} holds no built site",
        site.display()
    );
    let inventory = routes::inventory(site, commit)?;
    fs::create_dir_all(site.join(".well-known"))?;
    fs::write(site.join(".well-known/b10x-site.json"), manifest)
        .context("writing site provenance")?;
    fs::write(site.join(".well-known/b10x-routes.json"), inventory)
        .context("writing the route inventory")?;
    fs::write(site.join(".nojekyll"), "")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prose_escapes_braces_and_capitalised_tags_outside_code_only() {
        assert_eq!(
            prose("a {b} `{c}` <D> `<E>` <f> </G>"),
            "a \\{b} `{c}` &lt;D> `<E>` &lt;f> &lt;/G>"
        );
        assert!(pages::problems(&prose("x { y <Z> `{`")).is_empty());
    }

    #[test]
    fn a_manifest_names_the_commit_and_refuses_a_bad_one() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        assert!(
            site_manifest(commit)
                .unwrap()
                .contains(&format!("\"commit\": \"{commit}\""))
        );
        assert!(site_manifest("e86f43d").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&format!("{}\"", &commit[..39])).is_err());
    }
}
