import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['index', 'getting-started', 'status'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/roles',
        'concepts/the-loop',
        'concepts/decisions-and-messages',
        'concepts/the-guard',
        'concepts/instances-and-config',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/configure-an-instance',
        'guides/start-conductor',
        'guides/add-a-repository-rule',
        'guides/read-the-dashboard',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
